// app/layout.js (Next.js 14+)
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import "./globals.css";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"
import FloatingActionButton from "@/components/FloatingActionButton";
import FloatingChatButton from "@/components/FloatingChatButton";
import BotpressChat from "@/components/BotpressChat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "RivoRent - Find & Rent Properties Across America",
  description:
    "RivoRent helps you find the perfect rental home or apartment in the USA. Browse listings, view photos, and apply online effortlessly.",
  keywords: [
    "RivoRent",
    "rent apartments USA",
    "find rental homes",
    "apartment listings America",
    "lease apartments online",
    "property management tools",
    "short-term rentals",
    "long-term rentals",
    "apartments for rent",
    "houses for rent",
    "studio apartments for rent",
    "1 bedroom apartments",
    "2 bedroom apartments",
    "3 bedroom apartments",
    "luxury apartments for rent",
    "cheap apartments for rent",
    "affordable housing USA",
    "rental properties online",
    "vacation rentals USA",
    "condos for rent",
    "townhouses for rent",
    "pet-friendly apartments",
    "furnished apartments",
    "unfurnished apartments",
    "online lease applications",
    "rent payment online",
    "real estate USA",
    "real estate listings",
    "rental property management",
    "property leasing platform",
    "find apartments near me",
    "apartments in Cleveland",
    "apartments in New York",
    "apartments in Los Angeles",
    "apartments in Chicago",
    "apartments in Miami",
    "apartments in Houston",
    "apartments in San Francisco",
    "apartments in Boston",
    "apartments in Seattle",
    "apartments in Austin",
    "apartment search USA",
    "rental market USA",
    "house rental listings",
    "renting made easy",
    "residential rentals",
    "commercial rentals USA",
    "apartment finder",
    "apartment locator",
    "online property search",
    "real estate tools",
    "tenant resources",
    "landlord tools",
    "apartment deals",
    "rental offers",
    "move-in ready apartments",
    "apartment comparison",
    "rental guides",
    "lease online",
    "digital lease signing",
    "property management software",
    "property listings",
    "real estate marketplace",
    "find homes for rent",
    "best rental platform",
    "apartment reviews",
    "rental advice USA",
    "property search tool",
    "renting tips",
    "housing USA",
    "rental search engine",
    "real estate search",
    "apartment availability USA",
    "apartment booking online",
    "cheap houses for rent",
    "affordable apartments",
    "student housing USA",
    "family apartments for rent",
    "pet-friendly housing",
    "short-term apartment rental",
    "furnished short-term rentals",
    "monthly rentals USA",
    "yearly rentals USA",
    "lease apartments fast",
    "rental listings near me",
    "housing for students",
    "online apartment search",
    "find rental apartments fast",
    "best apartment deals USA",
    "apartment rental websites",
    "real estate online",
    "rent home online",
    "property listing service",
    "apartment search engine",
    "lease apartment online",
    "apartment lease application",
    "find houses for rent",
    "rental property finder",
    "property rental platform",
    "apartment availability online",
    "virtual apartment tour",
    "3D apartment tours",
    "apartments with amenities",
    "apartments with pool",
    "apartments with gym",
    "apartments with parking",
    "high-rise apartments",
    "downtown apartments",
    "suburban apartments",
    "modern apartments",
    "new construction apartments",
    "move-in ready homes",
    "houses near me",
    "luxury rentals USA",
    "affordable rentals USA",
    "rental listings by city",
    "rentals by state",
    "apartments in California",
    "apartments in Texas",
    "apartments in Florida",
    "apartments in New York State",
    "apartments in Illinois",
    "apartments in Pennsylvania",
    "apartments in Ohio",
    "apartments in Georgia",
    "apartments in Michigan",
    "apartments in North Carolina",
    "apartments in New Jersey",
    "apartments in Virginia",
    "apartments in Washington",
    "apartments in Arizona",
    "apartments in Massachusetts",
    "apartments in Tennessee",
    "apartments in Indiana",
    "apartments in Missouri",
    "apartments in Maryland",
    "apartments in Wisconsin",
    "apartments in Colorado",
    "apartments in Minnesota",
    "apartments in South Carolina",
    "apartments in Alabama",
    "apartments in Louisiana",
    "apartments in Kentucky",
    "apartments in Oregon",
    "apartments in Oklahoma",
    "apartments in Connecticut",
    "apartments in Iowa",
    "apartments in Mississippi",
    "apartments in Arkansas",
    "apartments in Utah",
    "apartments in Nevada",
    "apartments in Kansas",
    "apartments in New Mexico",
    "apartments in Nebraska",
    "apartments in West Virginia",
    "apartments in Idaho",
    "apartments in Hawaii",
    "apartments in Maine",
    "apartments in New Hampshire",
    "apartments in Montana",
    "apartments in Rhode Island",
    "apartments in Delaware",
    "apartments in South Dakota",
    "apartments in North Dakota",
    "apartments in Alaska",
    "apartments in Vermont",
    "apartments in Wyoming",
    "apartment listings California",
    "apartment listings Texas",
    "apartment listings Florida",
    "apartment listings New York",
    "apartment listings Illinois",
    "apartment listings Ohio",
    "apartment listings Pennsylvania",
    "apartment listings Michigan",
    "apartment listings Georgia",
    "apartment listings North Carolina",
    "vacation rentals California",
    "vacation rentals Florida",
    "vacation rentals New York",
    "vacation rentals Texas",
    "rental homes near me",
    "rental houses near me",
    "apartments for families",
    "rentals with backyard",
    "rentals with balcony",
    "student apartments",
    "student housing listings",
    "cheap student apartments",
    "online rental listings",
    "real estate listings USA",
    "residential property search",
    "find rental homes fast",
    "apartment comparison tool",
    "best rental websites",
    "rental search online",
    "rent apartment app",
    "rent house app",
    "find rental units",
    "monthly apartment rental",
    "yearly apartment rental",
    "apartment leasing service",
    "property management online",
    "property lease application",
    "lease apartment fast",
    "apartment for rent now",
    "rental homes for families",
    "rental listings for students",
    "real estate rental platform",
    "best rental listings",
    "property listings by city",
    "property listings by state",
    "short-term rental apartments",
    "long-term rental apartments",
    "lease apartment online USA",
    "online apartment lease",
    "digital lease signing",
    "rental application online",
    "apartment finder app",
    "apartment locator app",
    "real estate app USA",
    "find apartments app",
    "apartment search mobile",
    "housing search USA",
    "best rental app",
    "property search app",
    "find rental apartments app",
    "rentals app",
    "housing app USA",
    "apartment deals app",
    "rental offers app",
    "rent online USA",
    "property rental app",
    "lease online USA",
    "online housing platform",
    "real estate finder app",
    "best online rentals",
    "apartment listings app",
    "find homes for rent app",
    "student rentals app",
    "short-term housing app",
    "long-term housing app",
    "pet-friendly rentals app",
    "furnished apartment app",
    "move-in ready rentals",
    "new apartments listings",
    "latest apartment deals",
    "property search online USA",
    "rental search engine USA",
    "online property finder",
    "virtual apartment search",
    "3D property tours",
    "best real estate platform",
    "apartment reviews USA",
    "housing reviews USA",
    "real estate reviews",
    "tenant reviews",
    "landlord reviews",
    "rental guides USA",
    "apartment guides USA",
    "rental tips USA",
    "leasing tips",
    "renting advice USA",
    "real estate tips",
    "housing advice USA",
    "best apartments USA",
    "top rental platforms",
    "trusted rental websites",
    "find homes fast",
    "find apartments fast",
    "apartment deals USA",
    "rental deals USA",
    "monthly rental deals",
    "annual rental deals",
    "property listings updates",
    "housing updates USA",
    "new rental listings",
    "latest rental listings",
    "affordable housing platform",
    "rental housing platform",
    "USA rental marketplace",
    "online apartment marketplace",
    "digital rental platform",
    "rental solutions USA",
    "property solutions USA",
    "housing solutions USA",
    "find apartment near me app",
    "rent home near me",
    "rental properties near me",
    "apartments near me online",
    "lease apartment near me",
    "find student housing near me",
    "find luxury apartments near me",
    "find cheap apartments near me",
    "apartment rental comparison",
    "online housing comparison",
    "digital property comparison",
    "find best rental deals",
    "compare apartments for rent",
    "compare houses for rent",
    "rental property ratings",
    "housing ratings",
    "apartment ratings",
    "online rental ratings",
    "USA housing search",
    "apartment search USA online",
    "housing search platform",
    "property search USA online",
    "best property search",
    "find rental home fast online",
    "lease property online USA",
    "apartment lease platform",
    "digital housing marketplace",
    "apartment rental online USA",
    "housing rental platform",
    "top rental listings USA",
    "popular apartments for rent",
    "popular rental homes",
    "best rental offers",
    "rental website USA",
    "rental portal USA",
    "online rental portal",
    "lease property app",
    "find rental property app",
    "housing application online",
    "online leasing USA",
    "digital leasing platform",
    "virtual lease signing",
    "tenant portal USA",
    "landlord portal USA",
    "rent payment platform",
    "pay rent online",
    "online rental payment",
    "lease management software",
    "rental management tools",
    "property management online platform",
    "property management app",
    "apartment management tools",
    "best apartment management",
    "residential property management",
    "real estate management tools",
    "housing management platform",
    "property management services",
    "renting made simple USA",
    "easy apartment search",
    "easy housing search",
    "rent apartment hassle-free",
    "lease apartment hassle-free",
    "rental platform USA",
    "housing platform USA",
    "digital apartment platform",
    "find home online",
    "lease home online",
    "find rental unit fast",
    "apartment listings fast",
    "rental homes fast",
    "student apartments fast",
    "short-term rental fast",
    "long-term rental fast",
    "property listings fast",
    "rent apartment app USA",
    "find home app USA",
    "apartment locator USA",
    "rental locator USA",
    "housing locator app",
    "best housing app",
    "apartment listings mobile",
    "find rental home mobile",
    "renting mobile app",
    "property search mobile app",
    "digital housing app",
    "lease apartment mobile",
    "online lease mobile",
    "virtual housing platform",
    "3D virtual apartment tours",
    "interactive apartment search",
    "interactive rental listings",
    "apartment 3D tours online",
    "virtual apartment walkthrough",
    "rent home 3D tour",
    "find apartment 3D",
    "lease apartment 3D",
    "apartment deals online",
    "housing deals online",
    "rental offers online",
    "student housing deals",
    "family rental deals",
    "affordable housing online",
    "digital rental search",
    "apartment digital search",
    "property digital search",
    "best rental platform online",
    "top rental websites USA",
    "USA apartment listings online",
    "USA housing listings online",
    "find best apartments USA",
    "rentals USA online",
    "lease USA apartments",
    "property finder USA online",
    "apartment finder USA online",
    "best housing search USA",
    "residential property search online",
    "rent apartment near me USA",
    "lease apartment near me USA",
    "housing near me online",
    "find rental property near me",
    "apartment locator online",
    "housing locator online",
    "rental property online",
    "rental property USA online",
    "rental management online",
    "lease management software",
    "digital rent payment",
    "pay rent online platform",
    "rent payment online USA",
    "apartment reviews online",
    "rental reviews online",
    "housing reviews online",
    "property reviews online",
    "student housing reviews",
    "family housing reviews",
    "top rated apartments USA",
    "best apartments near me",
    "best houses near me",
    "online housing guide",
    "rental tips online",
    "apartment tips online",
    "leasing tips online",
    "renting tips online",
    "property advice online",
    "housing advice online",
    "best rental offers online",
    "latest rental listings USA",
    "new apartment listings USA",
    "new houses for rent USA",
    "online rental marketplace",
    "digital rental marketplace",
    "virtual rental platform",
    "rent online USA",
    "lease online USA",
    "digital leasing USA",
    "property rental app",
    "apartment rental app",
    "housing rental app",
    "top apartments for rent USA",
    "top rental homes USA",
    "popular apartments online",
    "popular rental homes online",
    "best online rentals USA",
    "affordable rental homes online",
    "luxury rental homes online",
    "best student apartments online",
    "best family apartments online",
    "move-in ready apartments online",
    "new rentals online",
    "updated apartment listings",
    "updated rental listings",
    "best housing deals",
    "find your apartment online",
    "lease your home online",
    "find home fast online",
    "rental platform mobile",
    "apartment platform mobile",
    "property platform mobile",
    "housing platform mobile",
  ],

  openGraph: {
    title: "RivoRent - Find & Rent Properties Across America",
    description:
      "RivoRent helps you find the perfect rental home or apartment in the USA. Browse listings, view photos, and apply online effortlessly.",
    url: "https://www.Rivo.Rent",
    siteName: "RivoRent",
    images: [
      {
        url: "https://www.Rivo.Rent/og-image.png",
        width: 1200,
        height: 630,
        alt: "RivoRent - Rental Properties USA",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "RivoRent - Find & Rent Properties Across America",
    description:
      "RivoRent helps you find the perfect rental home or apartment in the USA. Browse listings, view photos, and apply online effortlessly.",
    images: ["https://www.Rivo.Rent/og-image.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Structured Data (JSON-LD) */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "RealEstateAgent",
              name: "RivoRent",
              url: "https://www.Rivo.Rent",
              logo: "https://www.Rivo.Rent/logo.png",
              sameAs: [
                "https://www.facebook.com/share/17wEiW16gm/?mibextid=wwXIfr",
                "https://www.twitter.com/rivorent",
                "https://www.linkedin.com/company/rivorent",
              ],
              description:
                "RivoRent helps you find and rent apartments and homes across America with ease.",
              address: {
                "@type": "PostalAddress",
                addressLocality:
                  "200 Public Square Cleveland, OH  44114 United States",
                addressRegion: "OH",
                postalCode: "44101",
                addressCountry: "US",
              },
              contactPoint: {
                "@type": "ContactPoint",
                telephone: "+1-800-555-1234",
                contactType: "Customer Service",
              },
            }),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        <main className="flex-grow p-6">
          <SpeedInsights />
          {children} 
          <FloatingActionButton />
          <BotpressChat />
          <Analytics />
        </main>
        <Footer />
      </body>
    </html>
  );
}
